# Generated by Django 4.2.4 on 2023-09-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailApp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='DataEntry',
        ),
    ]
